### ISSUE TITLE
S2 atmospheric correction

### ISSUE THREAD

**Issue by MarcYin** [multiply-org/atmospheric_correction#1]
Hi @TonioF @gritk ,

This atmospheric correction method needs: 

Sentinel 2 data downloaded from AWS on a tile basis, which is much more convenient and reasonable compared to how ESA save the Sentinel 2 data); 
CAMS near real time prediction for each day at a time step of 3 hours with the start time of 00:00:00, and should contains aod550, tcwv and gtco3 parameters; 
a global DEM VRT file;
MCD43 collection 6 data from 3 days before to 3 days after the sentinel 2 observations;
you will also need the emulators for Sentinel 2 bands, which can be found at http://www2.geog.ucl.ac.uk/~ucfafyi/
The executable file is called Sentinel_atmo_cor.py which can be used as: python Sentinel_atmo_cor.py /directory/where/you/store/s2/data/29/S/QB/2017/9/4/0/ . No other options are needed for this version yet. It will correct for all bands and save them into the same directory of TOA reflectance with the name as B0?_sur.tif and a TOA_RGB.tif and BOA_RGB.tif is also composed for vision checking.

Further details are referred to  GitHub at https://github.com/multiply-org/atmospheric_correction

Thanks a lot,

Feng.

**Comment by TonioF** [comment]
Hi Feng,
thanks for the instructions. There is one issue with this, though: We should not delimit the atmospheric correction to S2 data from a specific place. It should work  with all formats that S2 data comes in. I guess this should be in place for the workshop, but surely at first we should put all effort in setting up one running version.

**Comment by MarcYin** [comment]
Dear Tonio,
 (Jose + Feng here)
The code requires the Amazon L1C data, which is easier to get hold of than the ESA data, and for which we have download code in grabba_grabba_hey. The ESA product has a mixture of different format versions, but I guess we can look at supporting other formats later on (for the demo all data is canned and downloaded)
