### ISSUE TITLE
AttributeError: Can't pickle local object

### ISSUE THREAD

**Issue by tcztzy** [multiply-org/atmospheric_correction#12]
I used to suffer the exceptions as the title said. I personally think if a nested function doesn't relay on the local variable of the parent's scoop, put this function on the top scoop is the better way.
[Python: AttributeError: Can't pickle local object 'writeBuf.<locals>.write'](https://stackoverflow.com/questions/45673841/python-attributeerror-cant-pickle-local-object-writebuf-locals-write)
[Can't pickle function](https://stackoverflow.com/questions/22157954/cant-pickle-function)
https://github.com/multiply-org/atmospheric_correction/blob/4a96b2655bc1a596571fc26db466ac7e9da6e930/SIAC/the_aerosol.py#L490-L496

https://github.com/multiply-org/atmospheric_correction/blob/4a96b2655bc1a596571fc26db466ac7e9da6e930/SIAC/the_aerosol.py#L643-L651

https://github.com/multiply-org/atmospheric_correction/blob/4a96b2655bc1a596571fc26db466ac7e9da6e930/SIAC/the_aerosol.py#L741-L749

https://github.com/multiply-org/atmospheric_correction/blob/4a96b2655bc1a596571fc26db466ac7e9da6e930/SIAC/the_correction.py#L347-L355

https://github.com/multiply-org/atmospheric_correction/blob/4a96b2655bc1a596571fc26db466ac7e9da6e930/SIAC/lhd.py#L202-L219

**Comment by MarcYin** [comment]
Thanks a lot for the suggestion and it has been integrated into the new commit 12bf54e8bad33dbd5df27c9e2d511faf16ffeee6.
