### ISSUE TITLE
Numpy dependency problem

### ISSUE THREAD

**Issue by tcztzy** [multiply-org/atmospheric_correction#15]
Numpy 1.18 introduce [this PR](https://github.com/numpy/numpy/pull/14800). And this PR will cause [the problem as I reported](https://github.com/numpy/numpy/pull/14800#commitcomment-37201191).

https://github.com/multiply-org/atmospheric_correction/blob/8d35a277ee7ba6fbb93bb6fef183e0b0166641f3/SIAC/atmo_solver.py#L277

https://github.com/multiply-org/atmospheric_correction/blob/8d35a277ee7ba6fbb93bb6fef183e0b0166641f3/SIAC/atmo_solver.py#L280

**Comment by MarcYin** [comment]
Add a ```.toarray()``` at the end of each sparse matrix should solve the problem, if I understand correctly.

```
 to_inv = np.nansum([sparse.diags((self.obs_unc[0]).ravel()).toarray(), sparse.diags((self.prior_uncs[0]**-2).ravel()).toarray(), self.gamma**2 * dtd.toarray()], axis = 0) 
```

```
to_inv = np.nansum([sparse.diags((self.obs_unc[1]).ravel()).toarray(), sparse.diags((self.prior_uncs[1]**-2).ravel()).toarray(), self.gamma**2 * dtd.toarray()], axis = 0)
```

**Comment by tcztzy** [comment]
I already tried `.toarray()`, but it will consume huge amount of memory (such as 23G or above) beyond your device capability. And this kind of memory allocation is useless since the matrix is spare and almost all element in matrix is zero.

**Comment by MarcYin** [comment]
ransom dose summation by ignoring the nan values in the array, so firstly set them to be 0s then do the summation. This also avoids the usage of numpy summation.

```
self.obs_unc[np.isnan(self.obs_unc)] = 0
self.prior_uncs[np.isnan(self.prior_uncs)] = 0

to_inv = sparse.diags((self.obs_unc[0]).ravel()) + sparse.diags((self.prior_uncs[0]**-2).ravel()) + self.gamma**2 * dtd

to_inv = sparse.diags((self.obs_unc[1]).ravel()) + sparse.diags((self.prior_uncs[1]**-2).ravel()) + self.gamma**2 * dtd
```

**Comment by MarcYin** [comment]
The above solution has been tested and added into the new commit 12bf54e8bad33dbd5df27c9e2d511faf16ffeee6:
https://github.com/multiply-org/atmospheric_correction/blob/12bf54e8bad33dbd5df27c9e2d511faf16ffeee6/SIAC/atmo_solver.py#L275-L287
