### ISSUE TITLE
SIAC may not work with GDAL>=3.0

### ISSUE THREAD

**Issue by tcztzy** [multiply-org/atmospheric_correction#9]
I used to install SIAC with pip, things worked fine before the process handling MCD43_VRT, I got the error message as "None object has no attributes named FlushCache", the detailed log message shows that it failed getting VRT files from HDR. The latest release of gdal in pypi is version 3.0.3, I downgrade gdal to 2.4.4, such problems solved.

**Comment by MarcYin** [comment]
It has worked fine with gdal 3.0.3 on my computer and the travis computers. This probably due to the installation of gdal, and the suggested method of installation is by the using of conda from conda-forge channel.
